### ISSUE TITLE
Boost field positive does not get populated

### ISSUE THREAD

**Issue by mathiasnohall** [elasticsearch/elasticsearch-net#1234] opened 2015-02-03 15:24 UTC
Im trying to do a boosting query that reduces the score of documents where the field with name "type" and with the value "Press".

However NEST does not generate any values in the positive field in the generated json object:

  "query": {
    "boosting": {
      "positive": {},
      "negative": {
        "term": {
          "type": {
            "value": "Press"
          }
        }
      },
      "negative_boost": 0.2
    }
  }

Code Bellow:

            var result = _elasticClient.Search<SearchablePage>(new SearchDescriptor<SearchablePage>()
                .Query(q => q
                    .Boosting(b => b
                        .NegativeBoost(0.2)
                        .Positive(p => p
                            .Filtered(fi => fi                        
                                .Filter(fq => fq
                                    .Term(t => t.Type, aggregation)
                                )
                                .Query(qq => qq
                                    .QueryString(qs => qs
                                        .Query(query)
                                        .OnFields(f => f.Name, f => f.Presentation, f => f.MainBody, f => f.SearchableBlocks.First().MainBody)
                                    )
                                )  
                            )
                        )
                        .Negative(n => n
                            .Term(f => f.OnField("type").Value("Press"))
                        )
                    )
                )
);

**Comment by gmarz** [comment] 2015-02-05 23:06
Hm, can't quite reproduce this.  What version of NEST are you on?

**Comment by mathiasnohall** [comment] 2015-02-06 07:56
using Nest 1.4 and elastic 1.4.2

But i solved it using Function Score

**Comment by gmarz** [comment] 2015-02-10 02:33
@mathiasnohall Glad you were able to find a work around, but this is still a bit unsettling.  Not sure why I can't reproduce this with practically the same code.

Would you mind sharing your `SearchablePage`

**Comment by gmarz** [comment] 2015-02-17 16:25
Closing since I can't reproduce.  @mathiasnohall feel free to reopen if you can provide more details, perhaps a test that successfully repros this.

**Closed by gmarz** 2015-02-17 16:25 UTC
