### ISSUE TITLE
How to use TypeNameHandling to TypeNameHandling.Auto for deserialization only

### ISSUE THREAD

**Issue by alexandrepepin** [elasticsearch/elasticsearch-net#1155] opened 2014-12-16 16:02 UTC
I need to set the TypeNameHandling to TypeNameHandling.Auto to deserialize my objects returned by elasticsearch. I set the settings

    new ConnectionSettings(uri).SetJsonSerializerSettingsModifier(s => s.TypeNameHandling = TypeNameHandling.Auto)

But this also change the type name handling of when sending the query. So Nest sends the query with multiple $type in it which doesn't work : 

	{
	  "_source": {
		"$type": "Nest.SearchSourceDescriptor`1[[Pelican.Web.Models.Search.EntityContainer`1[[Pelican.Models.FormModel, Pelican.Models]], Pelican.Web]], Nest",
		"include": [
		  "Name",
		  "Date",
		  "Data"
		]
	  },
	  "query": {
		"filtered": {
		  "$type": "Nest.FilteredQueryDescriptor`1[[Pelican.Web.Models.Search.EntityContainer`1[[Pelican.Models.FormModel, Pelican.Models]], Pelican.Web]], Nest",
		  "filter": {
			"terms": {
			  "Name": [
				"Document name"
			  ],
			  "execution": "or"
			}
		  }
		}
	  }
	}

So, how can I set the deserialization settings of Newtownsoft without touching the serialization?

**Comment by alexandrepepin** [comment] 2015-01-06 15:21
I think we should be able to set the settings for the deserialization without affecting the internal serialization settings of Nest

**Comment by Mpdreamz** [comment] 2015-01-15 10:01
@alexandrepepin the only way that would be possible if all our classes have dedicated jsonconverters for reading and writing for them to be completely isolated. Which would introduce a major strain on development if we have to maintain those manually.

Since this is now mainly a JSON.NET bug i'm closing this.

**Closed by Mpdreamz** 2015-01-15 10:01 UTC

**Comment by alexandrepepin** [comment] 2015-01-15 14:33
No, it is not a bug of Newtonsoft. He closed my issue also. The attribute applies to the contents of the dictionary (i.e. List<>), not the contents of the list. I can't use the property in my case. I really need to be able to change the deserialization settings

**Comment by Mpdreamz** [comment] 2015-01-15 15:56
Can you use: 

````
[JsonObject(TypeNameHandling)]
````

On `IMyInterfaceType` itself? Would that solve it?

**Comment by alexandrepepin** [comment] 2015-01-15 18:48
No, it does not work either. Here is a more complete example showing my use case

	static void Main(string[] args)
	{
		DataType data = new DataType();
		List<IMyInterfaceType> myInterfaceType = new List<IMyInterfaceType>();
		myInterfaceType.Add(new MyInterfaceImplementationType() { SomeProperty = "property" });
		myInterfaceType.Add(new MySecondInterfaceImplementationType() { SomeProperty = "property2" });
		data.Rows.Add("key", myInterfaceType);

		string serialized = JsonConvert.SerializeObject(data, new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.Auto });

		DataType deserialized = JsonConvert.DeserializeObject<DataType>(serialized);
	}

	public class DataType
	{
		public DataType()
		{
			Rows = new Dictionary<string, IEnumerable<IMyInterfaceType>>();
		}

		public Dictionary<string, IEnumerable<IMyInterfaceType>> Rows { get; private set; }
	}

	[JsonObject(ItemTypeNameHandling = TypeNameHandling.Auto)]
	public interface IMyInterfaceType
	{
		string SomeProperty { get; set; }
	}

	public class MyInterfaceImplementationType : IMyInterfaceType
	{
		public string SomeProperty { get; set; }
	}

	public class MySecondInterfaceImplementationType : IMyInterfaceType
	{
		public string SomeProperty { get; set; }
	}

I can't get the deserialization working without setting the `JsonSerializerSettings` to the same I used to serialize.

**Comment by Mpdreamz** [comment] 2015-01-15 19:40
Ok then while not a bug it should be a feature request on JSON.NET to be able to specify it at the interface level. 

I understand your frustration but we are all users of json.net here and your needs should be able to be specified locally on your scope only. By saying to us you expect to to alter a pretty intrusive setting globally without altering how *our* objects are serialized you are looking at it the wrong way IMO. 

You can write a custom converter for now and apply it to your `IMyInterfaceType` for the time being. With NEST 2.0 we are exploring options at generating the serializing/deserialization of our objects ahead of time (no longer relying on JSON.NET defaults (perhaps not using JSON.NET at all)) but this will take a while to implement.

**Comment by alexandrepepin** [comment] 2015-01-15 19:46
Ok I understand. Thanks for your help :)

**Comment by zaus** [comment] 2015-05-12 15:47
@alexandrepepin this may be a slightly old answer but I got here and there via google, so thought I'd share just in case it helped -- http://stackoverflow.com/questions/8030538/how-to-implement-custom-jsonconverter-in-json-net-to-deserialize-a-list-of-base

One of the answers looks like you could look for a specific property in the object to determine what to deserialize to.  [Another question](http://stackoverflow.com/questions/5780888/casting-interfaces-for-deserialization-in-json-net) suggested a try/parse model internally.

**Comment by ahmetsonmez** [comment] 2019-12-17 10:18
> Instead of globally setting the the type name handling you can also mark properties with:
> 
> ```
> [JsonProperty(TypeNameHandling = TypeNameHandling.Auto)]
> ```
> 
> There is also a `ItemTypeNameHandling` option if you are working with collections.
> 
> This is the safer way adding support for this only local to your objects.
> 
> Hope this solves your issue!

Thx for the info
